#!/usr/bin/env python3
"""Generate the UPM package's `Third Party Notices.md`.

`weva_core` statically links ICU, the Unicode character tables generated from
the UCD, Blink's WTF Decimal and the ada URL parser. The package ships that
binary, so it has to ship their notices with it -- BSD-3-Clause and the Unicode
licence both require the notice to travel with a binary distribution, and the
package's own LICENSE.md covers only Weva's MIT terms.

The Godot addon has done this since it shipped (hosts/godot/package_addon.py
bundles the same texts plus an SBOM). The Unity side never got the equivalent,
which is the gap this closes.

`Third Party Notices.md` at the package root is Unity's own convention for
this, so it needs one .meta rather than a directory of them, and shows up
where a consumer expects it.

The fonts are already handled: each .ttf sits beside its own OFL text inside
Runtime/Resources/Fonts, so they are referenced rather than repeated.

    python hosts/unity/bundle_notices.py [--check]

--check verifies the file is present and current without writing it, which is
what CI runs before packing.
"""
import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / 'Packages' / 'com.wevaui' / 'Third Party Notices.md'

# (heading, version/revision, licence name, path to the text in this repo)
COMPONENTS = [
    ('ICU4C', '78.3', 'Unicode Licence V3', 'third_party/icu/LICENSE.txt'),
    ('Unicode Character Database (generated tables)', '17.0.0', 'Unicode Licence V3',
     'third_party/unicode/LICENSE.txt'),
    ('Blink WTF Decimal', 'rev 9596b537e435c5c23d247cb7d9925d81e8f7707e', 'BSD-3-Clause',
     'third_party/decimal/LICENSE.txt'),
    ('ada URL parser (MIT option)', '4.0.0, rev b12a893a4580', 'MIT',
     'third_party/ada/LICENSE-MIT'),
    ('ada URL parser (Apache-2.0 option)', '4.0.0, rev b12a893a4580', 'Apache-2.0',
     'third_party/ada/LICENSE-APACHE'),
]

HEADER = """# Third-party notices

`Runtime/Native/Plugins/**/weva_core.*` is a native library built from this
package's engine core. It statically links the components listed below, and
their licences are reproduced in full here because a binary distribution
carries them.

Weva's own terms are in [`LICENSE.md`](LICENSE.md) (MIT) and are unaffected by
any of this.

| Component | Version | Licence |
|---|---|---|
{table}

The bundled fonts are licensed separately: each ships beside its own SIL Open
Font Licence text in `Runtime/Resources/Fonts`.

*Generated by `hosts/unity/bundle_notices.py`. Do not edit by hand.*
"""


def render():
    rows = '\n'.join('| {} | {} | {} |'.format(n, v, lic) for n, v, lic, _ in COMPONENTS)
    parts = [HEADER.format(table=rows)]
    for name, _version, lic, rel in COMPONENTS:
        src = ROOT / rel
        if not src.is_file():
            raise SystemExit('missing licence source: ' + rel)
        text = src.read_text(encoding='utf-8').rstrip('\n')
        parts.append('\n---\n\n## {}\n\n*{}*\n\n```\n{}\n```\n'.format(name, lic, text))
    return ''.join(parts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='verify without writing; nonzero exit if missing or stale')
    args = ap.parse_args()

    want = render()
    if args.check:
        if not OUT.is_file():
            print('Third Party Notices.md is missing', file=sys.stderr)
            print('run: python hosts/unity/bundle_notices.py', file=sys.stderr)
            return 1
        if OUT.read_text(encoding='utf-8') != want:
            print('Third Party Notices.md is stale', file=sys.stderr)
            print('run: python hosts/unity/bundle_notices.py', file=sys.stderr)
            return 1
        print('Third Party Notices.md is current (%d components)' % len(COMPONENTS))
        return 0

    OUT.write_text(want, encoding='utf-8', newline='\n')
    print('wrote %s (%d components, %d bytes)'
          % (OUT.relative_to(ROOT), len(COMPONENTS), len(want.encode('utf-8'))))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
