// <auto-generated> by hosts/unity/gen_bindings.py from weva_c.h, weva_unity.h. Do not edit; regenerate.
// Blittable P/Invoke surface of libweva's C ABI for the Unity host (weva_core plugin).
#nullable disable
using System;
using System.Runtime.InteropServices;

namespace Weva.Native
{
    internal enum weva_status : int
    {
        WEVA_OK = 0,
        WEVA_ERR_INVALID_ARGUMENT = 1,
        WEVA_ERR_PARSE = 2,
        WEVA_ERR_NOT_FOUND = 3,
        WEVA_ERR_UNSUPPORTED = 4,
        WEVA_ERR_INTERNAL = 5,
        WEVA_ERR_INVALID_STATE = 6,
    }

    internal enum weva_draw_kind : int
    {
        WEVA_DRAW_GEOMETRY = 0,
        WEVA_DRAW_BACKDROP_FILTER = 1,
        WEVA_DRAW_ROUNDED_RECT = 2,
    }

    internal enum weva_blend_mode : int
    {
        WEVA_BLEND_NORMAL = 0,
        WEVA_BLEND_MULTIPLY = 1,
        WEVA_BLEND_SCREEN = 2,
        WEVA_BLEND_OVERLAY = 3,
        WEVA_BLEND_DARKEN = 4,
        WEVA_BLEND_LIGHTEN = 5,
        WEVA_BLEND_COLOR_DODGE = 6,
        WEVA_BLEND_COLOR_BURN = 7,
        WEVA_BLEND_HARD_LIGHT = 8,
        WEVA_BLEND_SOFT_LIGHT = 9,
        WEVA_BLEND_DIFFERENCE = 10,
        WEVA_BLEND_EXCLUSION = 11,
        WEVA_BLEND_HUE = 12,
        WEVA_BLEND_SATURATION = 13,
        WEVA_BLEND_COLOR = 14,
        WEVA_BLEND_LUMINOSITY = 15,
    }

    internal enum weva_event_kind : int
    {
        WEVA_EVENT_NONE = 0,
        WEVA_EVENT_POINTER_DOWN = 1,
        WEVA_EVENT_POINTER_UP = 2,
        WEVA_EVENT_CLICK = 3,
        WEVA_EVENT_POINTER_ENTER = 4,
        WEVA_EVENT_POINTER_LEAVE = 5,
        WEVA_EVENT_KEY_DOWN = 6,
        WEVA_EVENT_KEY_UP = 7,
        WEVA_EVENT_TEXT_INPUT = 8,
        WEVA_EVENT_FOCUS = 9,
        WEVA_EVENT_BLUR = 10,
        WEVA_EVENT_VALUE_CHANGED = 11,
        WEVA_EVENT_CHANGE = 12,
        WEVA_EVENT_SUBMIT = 13,
        WEVA_EVENT_SCROLL = 14,
        WEVA_EVENT_TOGGLE = 15,
        WEVA_EVENT_CONTEXT_MENU = 16,
        WEVA_EVENT_COMPOSITION_START = 17,
        WEVA_EVENT_COMPOSITION_UPDATE = 18,
        WEVA_EVENT_COMPOSITION_END = 19,
        WEVA_EVENT_RESET = 20,
        WEVA_EVENT_CLOSE = 21,
        WEVA_EVENT_CANCEL = 22,
        WEVA_EVENT_INVALID = 23,
        WEVA_EVENT_BEFORE_TOGGLE = 24,
    }

    [Flags] internal enum weva_key_modifier : uint
    {
        WEVA_MOD_SHIFT = 1 << 0,
        WEVA_MOD_CTRL = 1 << 1,
        WEVA_MOD_ALT = 1 << 2,
        WEVA_MOD_META = 1 << 3,
    }

    internal enum weva_key : int
    {
        WEVA_KEY_OTHER = 0,
        WEVA_KEY_TAB = 1,
        WEVA_KEY_ENTER = 2,
        WEVA_KEY_SPACE = 3,
        WEVA_KEY_ESCAPE = 4,
        WEVA_KEY_BACKSPACE = 5,
        WEVA_KEY_DELETE = 6,
        WEVA_KEY_LEFT = 7,
        WEVA_KEY_RIGHT = 8,
        WEVA_KEY_UP = 9,
        WEVA_KEY_DOWN = 10,
        WEVA_KEY_HOME = 11,
        WEVA_KEY_END = 12,
        WEVA_KEY_PAGE_UP = 13,
        WEVA_KEY_PAGE_DOWN = 14,
    }

    internal enum weva_box_kind : int
    {
        WEVA_BOX_BLOCK = 0,
        WEVA_BOX_ANONYMOUS_BLOCK = 1,
        WEVA_BOX_INLINE = 2,
        WEVA_BOX_ANONYMOUS_INLINE = 3,
        WEVA_BOX_LINE = 4,
        WEVA_BOX_TEXT = 5,
    }

    [Flags] internal enum weva_pointer_button : uint
    {
        WEVA_BUTTON_PRIMARY = 1 << 0,
        WEVA_BUTTON_SECONDARY = 1 << 1,
        WEVA_BUTTON_MIDDLE = 1 << 2,
    }

    [Flags] internal enum weva_validity_error : uint
    {
        WEVA_VALIDITY_VALUE_MISSING = 1 << 0,
        WEVA_VALIDITY_TYPE_MISMATCH = 1 << 1,
        WEVA_VALIDITY_PATTERN_MISMATCH = 1 << 2,
        WEVA_VALIDITY_TOO_LONG = 1 << 3,
        WEVA_VALIDITY_TOO_SHORT = 1 << 4,
        WEVA_VALIDITY_RANGE_UNDERFLOW = 1 << 5,
        WEVA_VALIDITY_RANGE_OVERFLOW = 1 << 6,
        WEVA_VALIDITY_STEP_MISMATCH = 1 << 7,
        WEVA_VALIDITY_BAD_INPUT = 1 << 8,
        WEVA_VALIDITY_CUSTOM_ERROR = 1 << 9,
    }

    internal enum weva_change_kind : int
    {
        WEVA_CHANGE_PAINT = 1,
        WEVA_CHANGE_LAYOUT = 2,
        WEVA_CHANGE_BOXES = 3,
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_config
    {
        public int viewport_width;
        public int viewport_height;
        public double device_pixel_ratio;
        public double root_font_size;
        public int use_user_agent_stylesheet;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_vertex
    {
        public float x;
        public float y;
        public float r;
        public float g;
        public float b;
        public float a;
        public float u;
        public float v;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_rounded_rect
    {
        public double x;
        public double y;
        public double width;
        public double height;
        public fixed double radii[8]; // double radii[4][2]
        public float r;
        public float g;
        public float b;
        public float a;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_backdrop_effect
    {
        public double blur_radius;
        public fixed float color_matrix[9]; // float color_matrix[9]
        public fixed float color_offset[3]; // float color_offset[3]
        public float color_alpha;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_draw
    {
        public weva_vertex* vertices;
        public nuint vertex_count;
        public uint* indices;
        public nuint index_count;
        public ulong texture_id;
        public int scissor_x;
        public int scissor_y;
        public int scissor_width;
        public int scissor_height;
        public int has_scissor;
        public int kind;
        public weva_backdrop_effect backdrop;
        public weva_rounded_rect rounded_rect;
        public int blend_mode;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_texture
    {
        public ulong id;
        public byte* rgba;
        public int width;
        public int height;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_render_backend
    {
        public void* user_data;
        public delegate* unmanaged[Cdecl]<void*, weva_vertex*, nuint, uint*, nuint, ulong> compile_geometry;
        public delegate* unmanaged[Cdecl]<void*, ulong, float, float, ulong, void> render_geometry;
        public delegate* unmanaged[Cdecl]<void*, ulong, void> release_geometry;
        public delegate* unmanaged[Cdecl]<void*, byte*, int, int, ulong> generate_texture;
        public delegate* unmanaged[Cdecl]<void*, ulong, void> release_texture;
        public delegate* unmanaged[Cdecl]<void*, byte*, int*, int*, ulong> load_texture;
        public delegate* unmanaged[Cdecl]<void*, int, int, int, int, int, void> set_scissor;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_glyph_bitmap
    {
        public byte* alpha;
        public int width;
        public int height;
        public byte* rgba;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_font_backend
    {
        public void* user_data;
        public delegate* unmanaged[Cdecl]<void*, byte*, nuint, int, ulong> load_face;
        public delegate* unmanaged[Cdecl]<void*, ulong, double, double*, double*, double*, int> face_metrics;
        public delegate* unmanaged[Cdecl]<void*, ulong, uint, uint*, int> glyph_index;
        public delegate* unmanaged[Cdecl]<void*, ulong, uint, double, double*, double*, double*, int*, int*, int> glyph_metrics;
        public delegate* unmanaged[Cdecl]<void*, ulong, uint, double, weva_glyph_bitmap*, int> rasterize;
        public delegate* unmanaged[Cdecl]<void*, ulong, byte*, nuint, double, uint*, double*, uint*, nuint, nuint> shape;
        public delegate* unmanaged[Cdecl]<void*, ulong, int, int, ulong> variant;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_shaped_glyph
    {
        public uint glyph;
        public uint cluster;
        public double x_advance;
        public double y_advance;
        public double x_offset;
        public double y_offset;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_event
    {
        public int kind;
        public uint target;
        public double x;
        public double y;
        public uint buttons;
        public int key;
        public uint modifiers;
        public fixed byte text[8]; // char text[8]
        public fixed byte handler[48]; // char handler[48]
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_stats
    {
        public double update_ms;
        public double cascade_ms;
        public double animate_ms;
        public double boxes_ms;
        public double layout_ms;
        public double paint_ms;
        public ulong updates;
        public uint elements;
        public uint boxes;
        public uint draws;
        public uint textures;
        public uint texture_cache_hits;
        public uint texture_cache_misses;
        public ulong cascade_elements;
        public ulong cascade_pseudos;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_box
    {
        public uint parent;
        public uint kind;
        public uint element;
        public double x;
        public double y;
        public double width;
        public double height;
        public double margin_top;
        public double margin_right;
        public double margin_bottom;
        public double margin_left;
        public double border_top;
        public double border_right;
        public double border_bottom;
        public double border_left;
        public double padding_top;
        public double padding_right;
        public double padding_bottom;
        public double padding_left;
        public double scroll_x;
        public double scroll_y;
        public byte* text;
        public nuint text_length;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_binding_source
    {
        public void* user;
        public delegate* unmanaged[Cdecl]<void*, byte*, byte*, nuint, int*, nuint> value;
        public delegate* unmanaged[Cdecl]<void*, byte*, int> count;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct weva_element_change
    {
        public uint element;
        public int kind;
    }

    internal static unsafe partial class WevaNative
    {
        public const string Library = "weva_core";
        public const int WEVA_ABI_VERSION_MAJOR = 0;
        public const int WEVA_ABI_VERSION_MINOR = 41;
        public const uint WEVA_ELEMENT_NONE = 0xFFFFFFFFu;
        public const uint WEVA_BOX_NONE = 0xFFFFFFFFu;

        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_abi_version();
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_render_backend(System.IntPtr doc, weva_render_backend* backend);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_font_backend(System.IntPtr doc, weva_font_backend* backend, ulong face);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_set_font_shaper(System.IntPtr doc, delegate* unmanaged[Cdecl]<void*, ulong, byte*, nuint, double, weva_shaped_glyph*, nuint, nuint> shape);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_font_leading_rounding(System.IntPtr doc, int rounds);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_register_font_family(System.IntPtr doc, byte* family, ulong face);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern System.IntPtr weva_document_create(weva_config* config);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_destroy(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_load_html(System.IntPtr doc, byte* html, nuint length);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_add_css(System.IntPtr doc, byte* css, nuint length);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_set_css(System.IntPtr doc, byte* css, nuint length);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_reload_html(System.IntPtr doc, byte* html, nuint length);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_viewport(System.IntPtr doc, int width, int height);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_color_scheme(System.IntPtr doc, int dark);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_safe_area_insets(System.IntPtr doc, double top, double right, double bottom, double left);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_content_size(System.IntPtr doc, double* out_width, double* out_height);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_update(System.IntPtr doc, double dt_seconds);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_update_geometry(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_update_with_input_time(System.IntPtr doc, double animation_seconds, double input_seconds);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_needs_input_tick(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern ulong weva_document_draw_serial(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern ulong weva_document_interaction_version(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_is_animating(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern weva_draw* weva_document_draws(System.IntPtr doc, nuint* out_count);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern ulong* weva_document_draw_versions(System.IntPtr doc, nuint* out_count);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern weva_texture* weva_document_textures(System.IntPtr doc, nuint* out_count);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_document_query(System.IntPtr doc, byte* selector);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_bounds(System.IntPtr doc, uint element, double* out_x, double* out_y, double* out_width, double* out_height);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_poll_event(System.IntPtr doc, weva_event* @out);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_event_text(System.IntPtr doc, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_contains(System.IntPtr doc, uint ancestor, uint descendant);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_document_element_at(System.IntPtr doc, double x, double y);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_cursor(System.IntPtr doc, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_cursor_at(System.IntPtr doc, double x, double y, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_document_element_at_devtools(System.IntPtr doc, double x, double y);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_stats(System.IntPtr doc, weva_stats* @out);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_boxes(System.IntPtr doc, weva_box* @out, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_accepts_pointer(System.IntPtr doc, double x, double y);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern ulong weva_document_transient_version(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_dismiss_transients(System.IntPtr doc, ulong version);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_pointer(System.IntPtr doc, double x, double y, uint buttons);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_pointer_modifiers(System.IntPtr doc, double x, double y, uint buttons, uint modifiers);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_clear_pointer(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_key(System.IntPtr doc, int key, uint modifiers, int down);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_text_input(System.IntPtr doc, byte* utf8);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_try_text_input(System.IntPtr doc, byte* utf8);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_try_text_input_modifiers(System.IntPtr doc, byte* utf8, uint modifiers);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_paste_text(System.IntPtr doc, byte* utf8);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_document_text_input_target(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_document_text_input_candidate(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_set_composition(System.IntPtr doc, byte* utf8, int start, int end);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_commit_composition(System.IntPtr doc, byte* utf8);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_document_composition(System.IntPtr doc, int* start, int* end);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_caret_bounds(System.IntPtr doc, double* x, double* y, double* width, double* height);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_document_focus_next(System.IntPtr doc, int backwards);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_document_focus_step(System.IntPtr doc, int backwards, int wrap);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_document_focus_move(System.IntPtr doc, double dx, double dy);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_set_focus(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_document_focus(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_tooltip_delay(System.IntPtr doc, double seconds);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_key_repeat(System.IntPtr doc, double delay_seconds, double interval_seconds);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_double_click(System.IntPtr doc, double window_seconds, double distance_px);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_open_select(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_document_open_select_element(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_select_word_at(System.IntPtr doc, double x, double y);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_select_all(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_undo(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_redo(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_selected_text(System.IntPtr doc, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_selection(System.IntPtr doc, uint element, int* out_start, int* out_end);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_set_selection(System.IntPtr doc, uint element, int start, int end);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_set_selection_without_focus(System.IntPtr doc, uint element, int start, int end);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_binding_source(System.IntPtr doc, weva_binding_source* source);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_refresh_bindings(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_set_html(System.IntPtr doc, uint element, byte* html, nuint length);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_element_append_html(System.IntPtr doc, uint element, byte* html, nuint length);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_remove(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_query_all(System.IntPtr doc, byte* selector, uint* @out, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_scroll(System.IntPtr doc, double x, double y, double dx, double dy);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_set_scroll(System.IntPtr doc, uint element, double x, double y);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_scroll(System.IntPtr doc, uint element, double* out_x, double* out_y, double* out_max_x, double* out_max_y);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_scroll_into_view(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_set_style(System.IntPtr doc, uint element, byte* property, byte* value);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_style(System.IntPtr doc, uint element, byte* property, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_set_attribute(System.IntPtr doc, uint element, byte* name, byte* value);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_value(System.IntPtr doc, uint element, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern ulong weva_element_form_version(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_set_value(System.IntPtr doc, uint element, byte* value);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_reset_form(System.IntPtr doc, uint form);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_element_form(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_set_text(System.IntPtr doc, uint element, byte* text);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_attribute(System.IntPtr doc, uint element, byte* name, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_tag_name(System.IntPtr doc, uint element, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_show_dialog(System.IntPtr doc, uint element, int modal);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_close_dialog(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_request_close_dialog(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_prevent_default(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_set_custom_validity(System.IntPtr doc, uint element, byte* message);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_custom_validity(System.IntPtr doc, uint element, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_validity(System.IntPtr doc, uint element, uint* errors, int* will_validate);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_check_validity(System.IntPtr doc, uint element, int* valid);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_report_validity(System.IntPtr doc, uint element, int* valid);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_dialog_return_value(System.IntPtr doc, uint element, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_set_dialog_return_value(System.IntPtr doc, uint element, byte* value);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_close_dialog_with_value(System.IntPtr doc, uint element, byte* value);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_request_close_dialog_with_value(System.IntPtr doc, uint element, byte* value);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern void weva_document_set_popover_request_events(System.IntPtr doc, int enabled);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_request_show_popover(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_request_hide_popover(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_request_toggle_popover(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_show_popover(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_hide_popover(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_toggle_popover(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_set_base_path(System.IntPtr doc, byte* path);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_missing_assets(System.IntPtr doc, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_css_diagnostics(System.IntPtr doc, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_html_diagnostics(System.IntPtr doc, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_changed_elements(System.IntPtr doc, weva_element_change* @out, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern ulong weva_document_structure_version(System.IntPtr doc);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_font_faces(System.IntPtr doc, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_layout_dump(System.IntPtr doc, byte* source, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_element_parent(System.IntPtr doc, uint element);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_children(System.IntPtr doc, uint element, uint* @out, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_box_model(System.IntPtr doc, uint element, double* @out);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_matched_rules(System.IntPtr doc, uint element, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_computed_style_all(System.IntPtr doc, uint element, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_document_set_asset_reader(System.IntPtr doc, delegate* unmanaged[Cdecl]<void*, byte*, byte*, nuint, nuint> reader, void* user_data);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_computed_style(System.IntPtr doc, uint element, byte* property, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_model_path(System.IntPtr doc, uint element, byte* path, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_row(System.IntPtr doc, uint element, int* out_index, byte* key_buffer, nuint key_capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_element_has_attribute(System.IntPtr doc, uint element, byte* name);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_element_text(System.IntPtr doc, uint element, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_text_direction(byte* utf8, nuint length);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_char_mirror(uint codepoint);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern int weva_char_joining_type(uint codepoint);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint weva_char_script(uint codepoint);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_document_font_family_names(System.IntPtr doc, byte* buffer, nuint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl)]
        public static extern nuint weva_unity_sizeof(byte* struct_name);
    }
}
