if(NOT DEFINED PROBE OR NOT DEFINED MODE OR NOT DEFINED WORK)
    message(FATAL_ERROR "PROBE, MODE and WORK are required")
endif()
file(MAKE_DIRECTORY "${WORK}")
execute_process(COMMAND "${PROBE}" "${MODE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
file(WRITE "${WORK}/${MODE}.log" "${output}${error}\nExit: ${result}\n")
if(MODE STREQUAL "address")
    set(expected "ERROR: AddressSanitizer: heap-buffer-overflow")
elseif(MODE STREQUAL "undefined")
    set(expected "runtime error: signed integer overflow")
else()
    message(FATAL_ERROR "Unknown sanitizer probe: ${MODE}")
endif()
if(NOT "${result}" MATCHES "^-?[0-9]+$" OR result STREQUAL "0" OR
        NOT "${output}${error}" MATCHES "${expected}")
    message(FATAL_ERROR "${MODE} instrumentation did not reject the positive control; see ${WORK}/${MODE}.log")
endif()
message(STATUS "${MODE} instrumentation detected the deliberate error")
