#!/usr/bin/env python3
"""Generate Unicode 17.0 grapheme properties from checksum-pinned UCD files.

Download the files listed in SOURCES from https://www.unicode.org/Public/17.0.0/ucd/
and pass their containing directory. Generated data is covered by the Unicode
license in third_party/unicode/LICENSE.txt.
"""
import argparse
import hashlib
from pathlib import Path

SOURCES = {
    'GraphemeBreakProperty.txt': ('auxiliary/', 'd6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89'),
    'emoji-data.txt': ('emoji/', '2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b'),
    'DerivedCoreProperties.txt': ('', '24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08'),
    'DerivedCombiningClass.txt': ('extracted/', '191463abfbd202703c6fd6776a92a23ac44ec65e0476a7f95aa91ca492cef29b'),
    'PropList.txt': ('', '130dcddcaadaf071008bdfce1e7743e04fdfbc910886f017d9f9ac931d8c64dd'),
}
GCB = {name: i for i, name in enumerate(('Other', 'CR', 'LF', 'Control', 'Extend', 'ZWJ',
                                       'Regional_Indicator', 'Prepend', 'SpacingMark', 'L', 'V', 'T', 'LV', 'LVT'))}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('data', type=Path)
    args = parser.parse_args()
    properties = [0] * 0x110000
    for name, (_, checksum) in SOURCES.items():
        data = (args.data / name).read_bytes()
        if hashlib.sha256(data).hexdigest() != checksum:
            raise ValueError('Unexpected Unicode data: ' + name)
        for line in data.decode('utf-8').splitlines():
            fields = [field.strip() for field in line.split('#')[0].split(';')]
            if len(fields) < 2:
                continue
            if name == 'GraphemeBreakProperty.txt':
                if fields[1] in ('LV', 'LVT'):  # Hangul syllables are classified arithmetically.
                    continue
                value = GCB[fields[1]]
            elif name == 'emoji-data.txt':
                if fields[1] not in ('Extended_Pictographic', 'Emoji_Modifier_Base'):
                    continue
                value = 16 if fields[1] == 'Extended_Pictographic' else 128
            elif name == 'DerivedCombiningClass.txt':
                if fields[1] == '0':
                    continue
                value = 256
            elif name == 'PropList.txt':
                if fields[1] != 'Variation_Selector':
                    continue
                value = 512
            else:
                if fields[1] != 'InCB':
                    continue
                value = {'Consonant': 32, 'Linker': 64, 'Extend': 96}[fields[2]]
            ends = fields[0].split('..')
            first, last = int(ends[0], 16), int(ends[-1], 16)
            for cp in range(first, last + 1):
                properties[cp] |= value
    ranges = []
    first = 0
    for at in range(1, len(properties) + 1):
        if at == len(properties) or properties[at] != properties[first]:
            if properties[first]:
                ranges.append((first, at - 1, properties[first]))
            first = at
    output = ['// Generated by tools/generate_graphemes.py; Unicode 17.0.0.',
              '// Unicode License V3: third_party/unicode/LICENSE.txt.',
              'static constexpr PropertyRange kGraphemeProperties[] = {']
    output += [f'    {{0x{first:X}, 0x{last:X}, {value}}},' for first, last, value in ranges]
    output += ['};', '']
    destination = Path(__file__).resolve().parents[1] / 'libweva/src/grapheme_data.inc'
    destination.write_text('\n'.join(output), encoding='utf-8', newline='\n')
    print(f'{len(ranges)} property ranges: {destination}')


if __name__ == '__main__':
    main()
