#include "check.h"
void test_arena();
void test_intern();
void test_geometry();
void test_dom();
void test_html();
void test_html_parser();
void test_css_tokenizer();
void test_css_parser();
void test_css_value();
void test_css_color();
void test_css_calc();
void test_selector();
void test_selector_has();
void test_selector_match();
void test_property_registry();
void test_computed_style();
void test_lazy_inheritance();
void test_cascade_order();
void test_cascade_compute();
void test_variables();
void test_variables_in_cascade();
void test_media_queries();
void test_supports();
void test_conditional_rules_in_cascade();
void test_pseudo_elements();
void test_match_cache();
void test_env();
void test_attr();
void test_env_attr_in_cascade();
void test_logical_axes();
void test_logical_in_cascade();
void test_logical_vs_physical_order();
void test_logical_before_substitution();
void test_at_property_descriptor();
void test_at_property_validate();
void test_at_property_in_cascade();
void test_css_wide_keywords();
void test_revert();
void test_revert_layer_rollback();
void test_custom_property_keywords();
void test_box_tree();
void test_box_tree_removal();
void test_box_tree_replace();
void test_box_geometry();
void test_box_id_stability();
void test_box_reparenting();
void test_box_builder_display();
void test_box_builder_blockification();
void test_anonymous_block_wrapping();
void test_box_builder_text_and_multicol();
void test_resolve_length();
void test_resolve_border_width();
void test_font_size_resolution();
void test_font_size_em_chain_limit();
void test_line_height_resolution();
void test_box_sides();
void test_aspect_ratio_and_direction();
void test_box_model_edges();
void test_box_model_width();
void test_box_model_min_max();
void test_box_model_height_and_position();
void test_auto_margin_centering();
void test_shorthand_expansion_gap();
void test_shorthand_tokenizer();
void test_shorthand_edges();
void test_shorthand_border();
void test_shorthand_radius_and_axes();
void test_substitution_defers_expansion();
void test_margin_collapse_rules();
void test_block_stacking();
void test_sibling_margin_collapse();
void test_mixed_sign_chain();
void test_parent_child_collapse();
void test_self_collapsing_block();
void test_barriers_do_not_collapse();
void test_percent_height_chain();
void test_auto_height_clamps();
void test_float_keywords();
void test_float_context_queries();
void test_float_placement();
void test_float_does_not_advance_flow();
void test_clear();
void test_float_bfc_scoping();
void test_font_metrics();
void test_inline_item_collection();
void test_line_breaking();
void test_whitespace_collapsing();
void test_line_metrics_and_align();
void test_shrink_to_fit();
void test_forced_breaks();
void test_break_all();
void test_inline_fragments();
void test_inline_atoms();
void test_relative_positioning();
void test_absolute_containing_block();
void test_absolute_placement();
void test_offsets_and_zindex();
void test_out_of_flow_relayout();
void test_tessellate_rect();
void test_tessellate_rounded();
void test_radii_clamping();
void test_tessellate_border();
void test_paint_decorations();
void test_paint_tree_calls();
void test_software_raster_coverage();
void test_software_fill_rule();
void test_software_gradient();
void test_software_blending_and_scissor();
void test_software_texture_and_robustness();
void test_software_translation_and_output();
void test_end_to_end_render();
void test_stub_font();
void test_stub_shaping();
void test_glyph_atlas();
void test_text_geometry();
void test_text_end_to_end();
void test_abi_version_and_lifecycle();
void test_abi_load_and_update();
void test_abi_query_and_bounds();
void test_abi_attributes_and_text();
void test_abi_viewport_and_restyle();
void test_abi_texture_ids_are_all_published();
void test_abi_host_render_backend();
void test_abi_partial_backend_degrades();
void test_abi_host_font_backend();
int main() {
    test_arena();
    test_intern();
    test_geometry();
    test_dom();
    test_html();
    test_html_parser();
    test_css_tokenizer();
    test_css_parser();
    test_css_value();
    test_css_color();
    test_css_calc();
    test_selector();
    test_selector_has();
    test_selector_match();
    test_property_registry();
    test_computed_style();
    test_lazy_inheritance();
    test_cascade_order();
    test_cascade_compute();
    test_variables();
    test_variables_in_cascade();
    test_media_queries();
    test_supports();
    test_conditional_rules_in_cascade();
    test_pseudo_elements();
    test_match_cache();
    test_env();
    test_attr();
    test_env_attr_in_cascade();
    test_logical_axes();
    test_logical_in_cascade();
    test_logical_vs_physical_order();
    test_logical_before_substitution();
    test_at_property_descriptor();
    test_at_property_validate();
    test_at_property_in_cascade();
    test_css_wide_keywords();
    test_revert();
    test_revert_layer_rollback();
    test_custom_property_keywords();
    test_box_tree();
    test_box_tree_removal();
    test_box_tree_replace();
    test_box_geometry();
    test_box_id_stability();
    test_box_reparenting();
    test_box_builder_display();
    test_box_builder_blockification();
    test_anonymous_block_wrapping();
    test_box_builder_text_and_multicol();
    test_resolve_length();
    test_resolve_border_width();
    test_font_size_resolution();
    test_font_size_em_chain_limit();
    test_line_height_resolution();
    test_box_sides();
    test_aspect_ratio_and_direction();
    test_box_model_edges();
    test_box_model_width();
    test_box_model_min_max();
    test_box_model_height_and_position();
    test_auto_margin_centering();
    test_shorthand_expansion_gap();
    test_shorthand_tokenizer();
    test_shorthand_edges();
    test_shorthand_border();
    test_shorthand_radius_and_axes();
    test_substitution_defers_expansion();
    test_margin_collapse_rules();
    test_block_stacking();
    test_sibling_margin_collapse();
    test_mixed_sign_chain();
    test_parent_child_collapse();
    test_self_collapsing_block();
    test_barriers_do_not_collapse();
    test_percent_height_chain();
    test_auto_height_clamps();
    test_float_keywords();
    test_float_context_queries();
    test_float_placement();
    test_float_does_not_advance_flow();
    test_clear();
    test_float_bfc_scoping();
    test_font_metrics();
    test_inline_item_collection();
    test_line_breaking();
    test_whitespace_collapsing();
    test_line_metrics_and_align();
    test_shrink_to_fit();
    test_forced_breaks();
    test_break_all();
    test_inline_fragments();
    test_inline_atoms();
    test_relative_positioning();
    test_absolute_containing_block();
    test_absolute_placement();
    test_offsets_and_zindex();
    test_out_of_flow_relayout();
    test_tessellate_rect();
    test_tessellate_rounded();
    test_radii_clamping();
    test_tessellate_border();
    test_paint_decorations();
    test_paint_tree_calls();
    test_software_raster_coverage();
    test_software_fill_rule();
    test_software_gradient();
    test_software_blending_and_scissor();
    test_software_texture_and_robustness();
    test_software_translation_and_output();
    test_end_to_end_render();
    test_stub_font();
    test_stub_shaping();
    test_glyph_atlas();
    test_text_geometry();
    test_text_end_to_end();
    test_abi_version_and_lifecycle();
    test_abi_load_and_update();
    test_abi_query_and_bounds();
    test_abi_attributes_and_text();
    test_abi_viewport_and_restyle();
    test_abi_texture_ids_are_all_published();
    test_abi_host_render_backend();
    test_abi_partial_backend_degrades();
    test_abi_host_font_backend();
    std::printf("%d checks, %d failures\n", wevatest::checks, wevatest::failures);
    return wevatest::failures == 0 ? 0 : 1;
}
