#include "check.h"
void test_arena();
void test_intern();
void test_geometry();
void test_dom();
void test_html();
void test_html_parser();
void test_css_tokenizer();
void test_css_parser();
void test_css_value();
void test_css_color();
void test_css_calc();
void test_selector();
void test_selector_has();
void test_selector_match();
void test_property_registry();
void test_computed_style();
void test_lazy_inheritance();
void test_cascade_order();
void test_cascade_compute();
void test_cascade_layers();
void test_component_expansion();
void test_block_in_inline_empty_fragments();
void test_letter_spacing_restarts_at_a_line_break();
void test_variables();
void test_variables_in_cascade();
void test_media_queries();
void test_supports();
void test_conditional_rules_in_cascade();
void test_pseudo_elements();
void test_match_cache();
void test_env();
void test_attr();
void test_env_attr_in_cascade();
void test_logical_axes();
void test_logical_in_cascade();
void test_logical_vs_physical_order();
void test_logical_before_substitution();
void test_css_property_index();
void test_easing_curves();
void test_keyframes_parsing();
void test_keyframe_sampling();
void test_keyframes_run();
void test_time_parsing();
void test_value_interpolation();
void test_at_property_descriptor();
void test_at_property_validate();
void test_at_property_in_cascade();
void test_css_wide_keywords();
void test_revert();
void test_revert_layer_rollback();
void test_custom_property_keywords();
void test_box_tree();
void test_box_tree_removal();
void test_box_tree_replace();
void test_box_geometry();
void test_box_id_stability();
void test_box_reparenting();
void test_box_builder_display();
void test_box_builder_blockification();
void test_anonymous_block_wrapping();
void test_box_builder_text_and_multicol();
void test_resolve_length();
void test_resolve_border_width();
void test_font_size_resolution();
void test_font_size_em_chain_limit();
void test_line_height_resolution();
void test_box_sides();
void test_aspect_ratio_and_direction();
void test_box_model_edges();
void test_box_model_width();
void test_box_model_min_max();
void test_box_model_height_and_position();
void test_auto_margin_centering();
void test_shorthand_expansion_gap();
void test_shorthand_tokenizer();
void test_shorthand_edges();
void test_shorthand_border();
void test_shorthand_radius_and_axes();
void test_substitution_defers_expansion();
void test_margin_collapse_rules();
void test_block_stacking();
void test_sibling_margin_collapse();
void test_mixed_sign_chain();
void test_parent_child_collapse();
void test_self_collapsing_block();
void test_barriers_do_not_collapse();
void test_percent_height_chain();
void test_auto_height_clamps();
void test_float_keywords();
void test_float_context_queries();
void test_float_placement();
void test_float_does_not_advance_flow();
void test_clear();
void test_float_bfc_scoping();
void test_font_metrics();
void test_inline_item_collection();
void test_line_breaking();
void test_whitespace_collapsing();
void test_line_metrics_and_align();
void test_shrink_to_fit();
void test_forced_breaks();
void test_break_all();
void test_flex_main_axis();
void test_flex_cross_axis();
void test_flex_direction_and_order();
void test_grid_tracks();
void test_grid_items();
void test_grid_areas();
void test_size_containment();
void test_anonymous_box_inherits_line_height();
void test_multicol();
void test_inline_fragment_edges();
void test_flex_min_height_is_not_a_definite_height();
void test_flex_min_max_carry_the_frame();
void test_flex_auto_margins_on_main_axis();
void test_flex_column_item_height_is_definite_for_its_content();
void test_flex_container_min_height_makes_the_main_size_definite();
void test_grid_line_placement();
void test_grid_alignment();
void test_grid_auto_track_contributions();
void test_absolute_auto_width_shrinks_to_fit();
void test_absolute_descendant_keeps_its_size_after_the_ancestor();
void test_shorthand_font();
void test_flex_stretch_is_clamped_by_the_items_min_max();
void test_flex_row_min_height_is_the_line_cross_size();
void test_flex_row_max_content_sums_its_items();
void test_letter_spacing_widens_runs();
void test_inline_fragment_height_and_order();
void test_var_in_shorthand_expands_after_substitution();
void test_font_family_registry();
void test_flex_center_is_unsafe();
void test_flex_aspect_ratio_height_is_definite();
void test_grid_item_relaid_in_a_second_pass_drops_the_imposed_height();
void test_letter_spacing_counts_utf16_units();
void test_inline_box_opening_at_line_end_has_no_fragment_there();
void test_flex_percent_height_against_an_auto_parent_is_indefinite();
void test_grid_aspect_ratio_item_stretches_one_axis();
void test_flex_wrap();
void test_flex_column_items_do_not_shrink_below_their_content();
void test_flex_row_items_do_not_shrink_below_their_min_content();
void test_var_shorthand_expands_at_its_cascade_position();
void test_inline_em_font_size_resolves_against_the_parent();
void test_max_content_joins_wrapped_lines();
void test_flex_abspos_child_static_position_follows_alignment();
void test_grid_track_sizing_functions();
void test_inline_box_edges_take_space_on_the_line();
void test_grid_aspect_ratio_item_takes_the_larger_transfer();
void test_grid_subgrid();
void test_block_in_inline_splitting();
void test_leading_space_after_an_inline_start_is_dropped();
void test_preserved_newlines_force_line_breaks();
void test_button_vertical_centering_is_flow_only();
void test_intrinsic_width_ignores_auto_margins();
void test_grid_intrinsic_width_is_its_tracks();
void test_top_level_comparison_functions();
void test_flex_wrap_reverse_flips_item_alignment();
void test_flex_baseline_items_size_the_line();
void test_aspect_ratio_height_respects_box_sizing();
void test_table_fixed_layout_columns();
void test_table_border_spacing_and_auto_layout();
void test_table_colspan_and_rowspan();
void test_table_cells_stretch_and_vertical_align();
void test_table_row_groups_and_captions();
void test_table_visibility_collapse_and_column_hints();
void test_grid_stretched_rows_feed_back_into_columns();
void test_background_shorthand();
void test_backdrop_filter_colour();
void test_backdrop_filter_extent();
void test_backdrop_filter_blur();
void test_backdrop_filter_reaches_the_backend();
void test_backdrop_filter_is_under_the_background();
void test_border_as_thick_as_its_radius();
void test_gradient_parsing();
void test_gradient_sampling();
void test_background_rasterize_layers();
void test_paint_gradient_backgrounds_and_canvas();
void test_text_transform_at_build();
void test_pseudo_element_boxes();
void test_pseudo_counters_and_quotes();
void test_pseudo_content_from_inline_custom_property();
void test_inline_custom_property_feeds_var();
void test_color_mix();
void test_gradient_calc_stop_position();
void test_paint_form_control_marks();
void test_clip_triangles_polygon();
void test_paint_clip_path_and_rounded_overflow();
void test_paint_clip_follows_descendant_transform();
void test_paint_stacking_order();
void test_color_glyphs();
void test_paint_color_filters();
void test_box_shadow_blur_falloff();
void test_blur_and_padded_rasterize();
void test_paint_transform_rotates_geometry();
void test_font_weight_resolution();
void test_anonymous_block_inherits_text_align();
void test_inline_fragments();
void test_inline_atoms();
void test_relative_positioning();
void test_absolute_containing_block();
void test_absolute_placement();
void test_offsets_and_zindex();
void test_out_of_flow_relayout();
void test_tessellate_rect();
void test_tessellate_rounded();
void test_radii_clamping();
void test_tessellate_border();
void test_paint_decorations();
void test_clip_triangles();
void test_paint_tree_calls();
void test_software_raster_coverage();
void test_software_fill_rule();
void test_software_gradient();
void test_software_blending_and_scissor();
void test_software_texture_and_robustness();
void test_software_translation_and_output();
void test_end_to_end_render();
void test_stub_font();
void test_stub_shaping();
void test_glyph_atlas();
void test_text_geometry();
void test_text_end_to_end();
void test_blurred_text_shadow_is_one_blurred_run();
void test_abi_version_and_lifecycle();
void test_abi_load_and_update();
void test_abi_incremental_matches_fresh();
void test_abi_incremental_selector_reach();
void test_abi_events();
void test_abi_checkbox();
void test_abi_caret();
void test_abi_scroll_extent();
void test_abi_scroll_wheel();
void test_abi_scroll_moves_content();
void test_abi_scroll_nested();
void test_abi_scroll_set_and_clamp();
void test_abi_scroll_repaints();
void test_abi_scroll_into_view();
void test_abi_scroll_into_view_nested();
void test_abi_caret_is_drawn();
void test_abi_form_pseudo_classes();
void test_abi_radio_group();
void test_abi_range_drag();
void test_abi_range_step_and_bounds();
void test_abi_text_field_editing();
void test_abi_set_value_round_trips();
void test_abi_tab_navigation();
void test_abi_tabindex_order();
void test_abi_focus_skips_unreachable();
void test_abi_keyboard_events();
void test_abi_text_input();
void test_abi_element_contains();
void test_abi_set_text();
void test_abi_hit_testing();
void test_abi_hit_testing_opt_out();
void test_abi_hit_testing_through_padding();
void test_abi_hover_active_focus();
void test_abi_transition_runs();
void test_abi_transition_costs_nothing_when_idle();
void test_transition_shorthand_lists();
void test_abi_query_and_bounds();
void test_abi_attributes_and_text();
void test_abi_viewport_and_restyle();
void test_abi_content_size();
void test_abi_rounded_rect_primitive();
void test_abi_texture_ids_are_all_published();
void test_abi_host_render_backend();
void test_abi_partial_backend_degrades();
void test_abi_host_font_backend();
int main() {
    test_arena();
    test_intern();
    test_geometry();
    test_dom();
    test_html();
    test_html_parser();
    test_css_tokenizer();
    test_css_parser();
    test_css_value();
    test_css_color();
    test_css_calc();
    test_selector();
    test_selector_has();
    test_selector_match();
    test_property_registry();
    test_computed_style();
    test_lazy_inheritance();
    test_cascade_order();
    test_cascade_compute();
    test_cascade_layers();
    test_component_expansion();
    test_block_in_inline_empty_fragments();
    test_letter_spacing_restarts_at_a_line_break();
    test_variables();
    test_variables_in_cascade();
    test_media_queries();
    test_supports();
    test_conditional_rules_in_cascade();
    test_pseudo_elements();
    test_match_cache();
    test_env();
    test_attr();
    test_env_attr_in_cascade();
    test_logical_axes();
    test_logical_in_cascade();
    test_logical_vs_physical_order();
    test_logical_before_substitution();
    test_css_property_index();
    test_easing_curves();
    test_keyframes_parsing();
    test_keyframe_sampling();
    test_keyframes_run();
    test_time_parsing();
    test_value_interpolation();
    test_at_property_descriptor();
    test_at_property_validate();
    test_at_property_in_cascade();
    test_css_wide_keywords();
    test_revert();
    test_revert_layer_rollback();
    test_custom_property_keywords();
    test_box_tree();
    test_box_tree_removal();
    test_box_tree_replace();
    test_box_geometry();
    test_box_id_stability();
    test_box_reparenting();
    test_box_builder_display();
    test_box_builder_blockification();
    test_anonymous_block_wrapping();
    test_box_builder_text_and_multicol();
    test_resolve_length();
    test_resolve_border_width();
    test_font_size_resolution();
    test_font_size_em_chain_limit();
    test_line_height_resolution();
    test_box_sides();
    test_aspect_ratio_and_direction();
    test_box_model_edges();
    test_box_model_width();
    test_box_model_min_max();
    test_box_model_height_and_position();
    test_auto_margin_centering();
    test_shorthand_expansion_gap();
    test_shorthand_tokenizer();
    test_shorthand_edges();
    test_shorthand_border();
    test_shorthand_radius_and_axes();
    test_substitution_defers_expansion();
    test_margin_collapse_rules();
    test_block_stacking();
    test_sibling_margin_collapse();
    test_mixed_sign_chain();
    test_parent_child_collapse();
    test_self_collapsing_block();
    test_barriers_do_not_collapse();
    test_percent_height_chain();
    test_auto_height_clamps();
    test_float_keywords();
    test_float_context_queries();
    test_float_placement();
    test_float_does_not_advance_flow();
    test_clear();
    test_float_bfc_scoping();
    test_font_metrics();
    test_inline_item_collection();
    test_line_breaking();
    test_whitespace_collapsing();
    test_line_metrics_and_align();
    test_shrink_to_fit();
    test_forced_breaks();
    test_break_all();
    test_flex_main_axis();
    test_flex_cross_axis();
    test_flex_direction_and_order();
    test_grid_tracks();
    test_grid_items();
    test_grid_areas();
    test_size_containment();
    test_anonymous_box_inherits_line_height();
    test_multicol();
    test_inline_fragment_edges();
    test_flex_min_height_is_not_a_definite_height();
    test_flex_min_max_carry_the_frame();
    test_flex_auto_margins_on_main_axis();
    test_flex_column_item_height_is_definite_for_its_content();
    test_flex_container_min_height_makes_the_main_size_definite();
    test_grid_line_placement();
    test_grid_alignment();
    test_grid_auto_track_contributions();
    test_absolute_auto_width_shrinks_to_fit();
    test_absolute_descendant_keeps_its_size_after_the_ancestor();
    test_shorthand_font();
    test_flex_stretch_is_clamped_by_the_items_min_max();
    test_flex_row_min_height_is_the_line_cross_size();
    test_flex_row_max_content_sums_its_items();
    test_letter_spacing_widens_runs();
    test_inline_fragment_height_and_order();
    test_var_in_shorthand_expands_after_substitution();
    test_font_family_registry();
    test_flex_center_is_unsafe();
    test_flex_aspect_ratio_height_is_definite();
    test_grid_item_relaid_in_a_second_pass_drops_the_imposed_height();
    test_letter_spacing_counts_utf16_units();
    test_inline_box_opening_at_line_end_has_no_fragment_there();
    test_flex_percent_height_against_an_auto_parent_is_indefinite();
    test_grid_aspect_ratio_item_stretches_one_axis();
    test_flex_wrap();
    test_flex_column_items_do_not_shrink_below_their_content();
    test_flex_row_items_do_not_shrink_below_their_min_content();
    test_var_shorthand_expands_at_its_cascade_position();
    test_inline_em_font_size_resolves_against_the_parent();
    test_max_content_joins_wrapped_lines();
    test_flex_abspos_child_static_position_follows_alignment();
    test_grid_track_sizing_functions();
    test_inline_box_edges_take_space_on_the_line();
    test_grid_aspect_ratio_item_takes_the_larger_transfer();
    test_grid_subgrid();
    test_block_in_inline_splitting();
    test_leading_space_after_an_inline_start_is_dropped();
    test_preserved_newlines_force_line_breaks();
    test_button_vertical_centering_is_flow_only();
    test_intrinsic_width_ignores_auto_margins();
    test_grid_intrinsic_width_is_its_tracks();
    test_top_level_comparison_functions();
    test_flex_wrap_reverse_flips_item_alignment();
    test_flex_baseline_items_size_the_line();
    test_aspect_ratio_height_respects_box_sizing();
    test_table_fixed_layout_columns();
    test_table_border_spacing_and_auto_layout();
    test_table_colspan_and_rowspan();
    test_table_cells_stretch_and_vertical_align();
    test_table_row_groups_and_captions();
    test_table_visibility_collapse_and_column_hints();
    test_grid_stretched_rows_feed_back_into_columns();
    test_background_shorthand();
    test_backdrop_filter_colour();
    test_backdrop_filter_extent();
    test_backdrop_filter_blur();
    test_backdrop_filter_reaches_the_backend();
    test_backdrop_filter_is_under_the_background();
    test_border_as_thick_as_its_radius();
    test_gradient_parsing();
    test_gradient_sampling();
    test_background_rasterize_layers();
    test_paint_gradient_backgrounds_and_canvas();
    test_text_transform_at_build();
    test_pseudo_element_boxes();
    test_pseudo_counters_and_quotes();
    test_pseudo_content_from_inline_custom_property();
    test_inline_custom_property_feeds_var();
    test_color_mix();
    test_gradient_calc_stop_position();
    test_paint_form_control_marks();
    test_clip_triangles_polygon();
    test_paint_clip_path_and_rounded_overflow();
    test_paint_clip_follows_descendant_transform();
    test_paint_stacking_order();
    test_color_glyphs();
    test_paint_color_filters();
    test_box_shadow_blur_falloff();
    test_blur_and_padded_rasterize();
    test_paint_transform_rotates_geometry();
    test_font_weight_resolution();
    test_anonymous_block_inherits_text_align();
    test_inline_fragments();
    test_inline_atoms();
    test_relative_positioning();
    test_absolute_containing_block();
    test_absolute_placement();
    test_offsets_and_zindex();
    test_out_of_flow_relayout();
    test_tessellate_rect();
    test_tessellate_rounded();
    test_radii_clamping();
    test_tessellate_border();
    test_paint_decorations();
    test_clip_triangles();
    test_paint_tree_calls();
    test_software_raster_coverage();
    test_software_fill_rule();
    test_software_gradient();
    test_software_blending_and_scissor();
    test_software_texture_and_robustness();
    test_software_translation_and_output();
    test_end_to_end_render();
    test_stub_font();
    test_stub_shaping();
    test_glyph_atlas();
    test_text_geometry();
    test_text_end_to_end();
    test_blurred_text_shadow_is_one_blurred_run();
    test_abi_version_and_lifecycle();
    test_abi_load_and_update();
    test_abi_incremental_matches_fresh();
    test_abi_incremental_selector_reach();
    test_abi_events();
    test_abi_checkbox();
    test_abi_caret();
    test_abi_scroll_extent();
    test_abi_scroll_wheel();
    test_abi_scroll_moves_content();
    test_abi_scroll_nested();
    test_abi_scroll_set_and_clamp();
    test_abi_scroll_repaints();
    test_abi_scroll_into_view();
    test_abi_scroll_into_view_nested();
    test_abi_caret_is_drawn();
    test_abi_form_pseudo_classes();
    test_abi_radio_group();
    test_abi_range_drag();
    test_abi_range_step_and_bounds();
    test_abi_text_field_editing();
    test_abi_set_value_round_trips();
    test_abi_tab_navigation();
    test_abi_tabindex_order();
    test_abi_focus_skips_unreachable();
    test_abi_keyboard_events();
    test_abi_text_input();
    test_abi_element_contains();
    test_abi_set_text();
    test_abi_hit_testing();
    test_abi_hit_testing_opt_out();
    test_abi_hit_testing_through_padding();
    test_abi_hover_active_focus();
    test_abi_transition_runs();
    test_abi_transition_costs_nothing_when_idle();
    test_transition_shorthand_lists();
    test_abi_query_and_bounds();
    test_abi_attributes_and_text();
    test_abi_viewport_and_restyle();
    test_abi_content_size();
    test_abi_rounded_rect_primitive();
    test_abi_texture_ids_are_all_published();
    test_abi_host_render_backend();
    test_abi_partial_backend_degrades();
    test_abi_host_font_backend();
    std::printf("%d checks, %d failures\n", wevatest::checks, wevatest::failures);
    return wevatest::failures == 0 ? 0 : 1;
}
