void test_abi_incremental_block_margins();
void test_abi_incremental_multicol_sizing();
void test_abi_incremental_collapsed_table_borders();
void test_abi_incremental_has_range_scopes();
void test_validity_selectors_chrome();
void test_range_selectors_chrome();
#include "check.h"
void test_arena();
void test_grapheme_conformance();
void test_abi_text_editing_boundaries();
void test_abi_maxlength_insertions();
void test_abi_maxlength_newlines();
void test_abi_maxlength_composition();
void test_abi_input_text_scroll();
void test_abi_text_advances_and_password();
void test_intern();
void test_word_motion_over_ascii();
void test_word_motion_over_punctuation();
void test_word_motion_over_cjk();
void test_word_selection_picks_one_unit();
void test_utf8_walking_never_splits_a_character();
void test_cjk_classification();
void test_accented_latin_is_a_word_character();
void test_geometry();
void test_dom();
void test_form_live_defaults();
void test_select_keyboard_ranges();
void test_select_pointer_ranges();
void test_select_display_size();
void test_select_disabled_dropdown();
void test_select_retained_paint();
void test_unicode_typeahead();
void test_select_typeahead_actions();
void test_select_labels();
void test_select_autoscroll();
void test_text_autoscroll();
void test_text_autoscroll_lifecycle();
void test_abi_incremental_text_autoscroll();
void test_abi_incremental_direct_text();
void test_abi_incremental_bindings();
void test_abi_incremental_caret_reuse();
void test_abi_incremental_keyed_reorder();
void test_abi_incremental_container_queries();
void test_abi_incremental_modal_layout();
void test_abi_inline_fragment_bounds();
void test_select_autoscroll_lifecycle();
void test_abi_incremental_select_autoscroll();
void test_abi_incremental_select_color_scopes();
void test_abi_form_reset();
void test_abi_incremental_form_state();
void test_abi_incremental_backdrop_lifecycle();
void test_abi_reset_edit_session();
void test_html();
void test_html_parser();
void test_css_tokenizer();
void test_css_parser();
void test_css_value();
void test_css_color();
void test_css_calc();
void test_selector();
void test_selector_has();
void test_selector_match();
void test_property_registry();
void test_computed_style();
void test_lazy_inheritance();
void test_cascade_order();
void test_cascade_compute();
void test_cascade_layers();
void test_component_expansion();
void test_block_in_inline_empty_fragments();
void test_letter_spacing_restarts_at_a_line_break();
void test_variables();
void test_variables_in_cascade();
void test_media_queries();
void test_container_size_queries();
void test_container_conditional_cascade();
void test_supports();
void test_conditional_rules_in_cascade();
void test_pseudo_elements();
void test_match_cache();
void test_env();
void test_attr();
void test_env_attr_in_cascade();
void test_logical_axes();
void test_logical_in_cascade();
void test_logical_vs_physical_order();
void test_logical_before_substitution();
void test_css_property_index();
void test_easing_curves();
void test_keyframes_parsing();
void test_keyframe_sampling();
void test_keyframes_run();
void test_time_parsing();
void test_value_interpolation();
void test_at_property_descriptor();
void test_at_property_validate();
void test_at_property_in_cascade();
void test_css_wide_keywords();
void test_revert();
void test_revert_layer_rollback();
void test_custom_property_keywords();
void test_box_tree();
void test_box_tree_removal();
void test_box_tree_replace();
void test_box_tree_move_owns_text();
void test_box_geometry();
void test_box_id_stability();
void test_box_reparenting();
void test_box_subtree_storage_lifetime();
void test_box_builder_display();
void test_box_builder_blockification();
void test_anonymous_block_wrapping();
void test_box_builder_text_and_multicol();
void test_resolve_length();
void test_resolve_border_width();
void test_font_size_resolution();
void test_font_size_inheritance_chain();
void test_line_height_resolution();
void test_line_height_inheritance();
void test_box_sides();
void test_aspect_ratio_and_direction();
void test_box_model_edges();
void test_box_model_width();
void test_box_model_min_max();
void test_box_model_height_and_position();
void test_auto_margin_centering();
void test_shorthand_expansion_gap();
void test_shorthand_tokenizer();
void test_shorthand_edges();
void test_anchor_sides();
void test_anchor_far_edge_properties();
void test_anchor_size();
void test_anchor_naming();
void test_anchor_invalid_falls_back();
void test_anchor_percentage();
void test_anchor_registry();
void test_shorthand_columns();
void test_shorthand_flex_flow();
void test_shorthand_text_decoration();
void test_shorthand_border();
void test_shorthand_radius_and_axes();
void test_substitution_defers_expansion();
void test_block_auto_margins();
void test_margin_collapse_rules();
void test_block_stacking();
void test_sibling_margin_collapse();
void test_mixed_sign_chain();
void test_parent_child_collapse();
void test_self_collapsing_block();
void test_barriers_do_not_collapse();
void test_percent_height_chain();
void test_auto_height_clamps();
void test_float_keywords();
void test_float_context_queries();
void test_float_placement();
void test_float_does_not_advance_flow();
void test_clear();
void test_float_bfc_scoping();
void test_font_metrics();
void test_inline_item_collection();
void test_line_breaking();
void test_whitespace_collapsing();
void test_line_metrics_and_align();
void test_shrink_to_fit();
void test_inline_layout_reuse();
void test_forced_breaks();
void test_form_control_baselines();
void test_break_all();
void test_flex_main_axis();
void test_flex_cross_axis();
void test_flex_direction_and_order();
void test_grid_tracks();
void test_grid_items();
void test_grid_areas();
void test_size_containment();
void test_anonymous_box_inherits_line_height();
void test_multicol();
void test_inline_fragment_edges();
void test_flex_min_height_is_not_a_definite_height();
void test_flex_min_max_carry_the_frame();
void test_flex_auto_margins_on_main_axis();
void test_flex_column_item_height_is_definite_for_its_content();
void test_flex_container_min_height_makes_the_main_size_definite();
void test_grid_named_lines_repeat_and_implicit_tracks();
void test_grid_line_placement();
void test_grid_stretch_respects_bounds_and_margins();
void test_grid_alignment();
void test_grid_auto_track_contributions();
void test_absolute_auto_width_shrinks_to_fit();
void test_absolute_descendant_keeps_its_size_after_the_ancestor();
void test_shorthand_font();
void test_flex_fractional_factors_and_padding();
void test_flex_stretch_is_clamped_by_the_items_min_max();
void test_flex_row_min_height_is_the_line_cross_size();
void test_flex_row_max_content_sums_its_items();
void test_letter_spacing_widens_runs();
void test_inline_fragment_height_and_order();
void test_var_in_shorthand_expands_after_substitution();
void test_font_family_registry();
void test_flex_center_is_unsafe();
void test_flex_aspect_ratio_height_is_definite();
void test_grid_item_relaid_in_a_second_pass_drops_the_imposed_height();
void test_inline_wrapped_fragments_keep_element_identity();
void test_letter_spacing_counts_graphemes();
void test_inline_box_opening_at_line_end_has_no_fragment_there();
void test_flex_percent_height_against_an_auto_parent_is_indefinite();
void test_grid_aspect_ratio_border_feedback_preserves_auto_height();
void test_grid_aspect_ratio_item_stretches_one_axis();
void test_flex_wrap();
void test_flex_column_items_do_not_shrink_below_their_content();
void test_flex_row_items_do_not_shrink_below_their_min_content();
void test_var_shorthand_expands_at_its_cascade_position();
void test_inline_em_font_size_resolves_against_the_parent();
void test_max_content_joins_wrapped_lines();
void test_parent_intrinsic_measurements();
void test_flex_abspos_child_static_position_follows_alignment();
void test_grid_track_sizing_functions();
void test_inline_box_edges_take_space_on_the_line();
void test_grid_aspect_ratio_item_takes_the_larger_transfer();
void test_grid_subgrid();
void test_grid_inline_atom_percentage_contribution();
void test_grid_auto_flow_column();
void test_grid_auto_flow_dense();
void test_block_in_inline_splitting();
void test_leading_space_after_an_inline_start_is_dropped();
void test_preserved_newlines_force_line_breaks();
void test_pre_wrap_soft_wraps();
void test_button_vertical_centering_is_flow_only();
void test_intrinsic_width_ignores_auto_margins();
void test_grid_intrinsic_width_is_its_tracks();
void test_top_level_comparison_functions();
void test_flex_wrap_reverse_flips_item_alignment();
void test_flex_baseline_items_size_the_line();
void test_flex_grid_item_formatting_context();
void test_border_box_floors_at_its_own_frame();
void test_aspect_ratio_height_respects_box_sizing();
void test_table_fixed_layout_columns();
void test_table_border_conflicts();
void test_table_border_grid();
void test_table_collapsed_border_geometry();
void test_table_collapsed_border_paint();
void test_table_positioned_content_order();
void test_table_nested_stacking_order();
void test_table_opacity_stacking();
void test_positioned_overflow_containing_blocks();
void test_table_translucent_border_intersections();
void test_table_unequal_border_intersections();
void test_table_collapsed_content_box_width();
void test_table_border_spacing_and_auto_layout();
void test_table_colspan_and_rowspan();
void test_table_cells_stretch_and_vertical_align();
void test_table_row_groups_and_captions();
void test_table_visibility_collapse_and_column_hints();
void test_grid_stretched_rows_feed_back_into_columns();
void test_image_decode();
void test_focus_move();
void test_background_image();
void test_replaced_image_cache();
void test_background_size_independence();
void test_blur_flat_matches_full();
void test_blur_matches_scalar();
void test_replaced_img();
void test_border_image();
void test_background_shorthand();
void test_backdrop_filter_colour();
void test_backdrop_filter_extent();
void test_backdrop_filter_blur();
void test_backdrop_filter_reaches_the_backend();
void test_backdrop_filter_is_under_the_background();
void test_border_as_thick_as_its_radius();
void test_gradient_parsing();
void test_gradient_sampling();
void test_gradient_prepared_color_spans();
void test_background_rasterize_layers();
void test_paint_gradient_backgrounds_and_canvas();
void test_text_transform_at_build();
void test_pseudo_element_boxes();
void test_pseudo_counters_and_quotes();
void test_pseudo_content_from_inline_custom_property();
void test_inline_custom_property_feeds_var();
void test_color_mix();
void test_gradient_calc_stop_position();
void test_paint_form_control_marks();
void test_clip_triangles_polygon();
void test_software_interior_clip_is_invisible();
void test_paint_clip_path_and_rounded_overflow();
void test_paint_clip_follows_descendant_transform();
void test_paint_stacking_order();
void test_color_glyphs();
void test_paint_color_filters();
void test_box_shadow_blur_falloff();
void test_blur_and_padded_rasterize();
void test_paint_transform_rotates_geometry();
void test_font_weight_resolution();
void test_anonymous_block_inherits_text_align();
void test_inline_fragments();
void test_inline_atoms();
void test_cjk_lines_break_between_characters();
void test_cjk_kinsoku_prohibitions();
void test_cjk_does_not_break_latin_runs();
void test_text_overflow_ellipsis();
void test_text_overflow_conditions();
void test_list_markers();
void test_list_marker_ordinals();
void test_list_marker_does_not_inherit_the_items_box();
void test_marker_pseudo_styles_the_marker();
void test_flex_flow_reaches_layout();
void test_text_indent();
void test_tabs_are_expanded_not_measured();
void test_tab_size();
void test_break_word_keeps_words_whole_when_they_fit();
void test_overflow_wrap_break_word();
void test_word_spacing_affects_wrapping();
void test_word_spacing();
void test_relative_positioning();
void test_absolute_containing_block();
void test_absolute_placement();
void test_offsets_and_zindex();
void test_out_of_flow_relayout();
void test_tessellate_rect();
void test_tessellate_rounded();
void test_radii_clamping();
void test_tessellate_border();
void test_tessellate_border_uneven_widths();
void test_paint_decorations();
void test_border_side_colors_and_bevels();
void test_srgb_byte_lookup_exact();
void test_paint_color_resolution();
void test_clip_triangles();
void test_paint_tree_calls();
void test_paint_registered_font_families();
void test_software_raster_coverage();
void test_software_fill_rule();
void test_software_gradient();
void test_software_blending_and_scissor();
void test_software_texture_and_robustness();
void test_software_translation_and_output();
void test_end_to_end_render();
void test_stub_font();
void test_stub_shaping();
void test_glyph_atlas();
void test_text_geometry();
void test_text_end_to_end();
void test_blurred_text_shadow_is_one_blurred_run();
void test_abi_version_and_lifecycle();
void test_abi_stylesheet_replacement();
void test_abi_field_selection_memory();
void test_abi_selection_default_lifecycle();
void test_abi_load_and_update();
void test_abi_incremental_matches_fresh();
void test_abi_incremental_subtree_sequences();
void test_abi_incremental_retained_grid_paint();
void test_abi_draw_versions();
void test_abi_incremental_glyph_preparation();
void test_abi_incremental_flex_intrinsics();
void test_abi_incremental_grid_animation();
void test_abi_incremental_corpus();
void test_abi_incremental_textarea_reflow();
void test_abi_incremental_selector_reach();
void test_abi_events();
void test_abi_checkbox();
void test_abi_caret();
void test_abi_binding_text();
void test_abi_binding_attributes();
void test_c_abi_binding_boolean_attributes();
void test_abi_binding_classes();
void test_abi_binding_without_a_source();
void test_abi_binding_long_values();
void test_abi_binding_value_changes_during_read();
void test_abi_binding_repeat();
void test_abi_binding_repeat_keeps_rows();
void test_abi_binding_repeat_scope();
void test_abi_event_handlers();
void test_abi_change_event();
void test_abi_submit_event();
void test_abi_scroll_event();
void test_abi_append_html();
void test_abi_set_html();
void test_abi_remove_element();
void test_abi_remove_clears_state();
void test_abi_query_all();
void test_abi_mutation_keeps_scroll();
void test_abi_scroll_extent();
void test_abi_scroll_wheel();
void test_abi_scroll_moves_content();
void test_abi_scroll_nested();
void test_abi_scroll_set_and_clamp();
void test_abi_scroll_repaints();
void test_abi_scroll_into_view();
void test_abi_scroll_into_view_nested();
void test_abi_scrollbar_appears();
void test_abi_scrollbar_drag();
void test_abi_scrollbar_track_click();
void test_abi_scrollbar_drag_does_not_click();
void test_abi_hidden_is_not_a_scroller();
void test_abi_scroll_keys();
void test_abi_scroll_keys_yield();
void test_abi_caret_is_drawn();
void test_abi_textarea_edits_its_content();
void test_abi_textarea_newlines();
void test_abi_textarea_line_keys();
void test_abi_textarea_caret();
void test_abi_textarea_scrolls_to_caret();
void test_abi_selection_keys();
void test_abi_word_motion_keys();
void test_abi_word_delete_keys();
void test_abi_document_extent_keys();
void test_abi_word_selection_over_cjk();
void test_abi_undo_groups_typing();
void test_abi_undo_breaks_on_other_edits();
void test_abi_undo_restores_cursor_and_forgets_scripted_writes();
void test_abi_undo_is_per_field();
void test_abi_details_toggles();
void test_abi_details_only_its_own_summary();
void test_abi_details_reports_the_toggle();
void test_abi_dialog_backdrop();
void test_abi_dialog_close_notification();
void test_abi_dialog_cancel_request();
void test_abi_dialog_cancel_survives_notifications();
void test_abi_dialog_escape_policy();
void test_abi_dialog_attribute_open_order();
void test_abi_dialog_return_values();
void test_abi_dialog_form_submission();
void test_abi_dialog_form_submission_overrides();
void test_abi_dialog_submission_lifecycle();
void test_form_required_validation();
void test_form_number_validation();
void test_form_email_validation();
void test_abi_email_validation();
void test_form_url_validation();
void test_form_length_validation();
void test_abi_length_validation();
void test_form_length_edit_origin();
void test_form_temporal_values();
void test_form_temporal_constraints();
void test_form_number_edit_buffer();
void test_abi_number_edit_history();
void test_form_number_filter();
void test_abi_temporal_constraints();
void test_abi_url_validation();
void test_form_custom_validity();
void test_abi_custom_validity();
void test_abi_validity_snapshot();
void test_abi_explicit_validity();
void test_abi_interaction_version();
void test_abi_range_directions();
void test_number_keyboard_steps();
void test_abi_invalid_reporting_lifecycle();
void test_abi_number_submission();
void test_abi_required_submission();
void test_abi_dialog_submission_handler_mutations();
void test_abi_bound_dialog_open_order();
void test_abi_label_activates_its_control();
void test_abi_label_forwarding_edge_cases();
void test_abi_popover_backdrop();
void test_abi_popover_trigger();
void test_abi_popover_target_action();
void test_abi_popover_light_dismiss();
void test_abi_popover_light_dismiss_after_trigger();
void test_abi_popover_escape_walks_the_stack();
void test_abi_popover_joins_the_top_layer();
void test_abi_hit_follows_paint_order();
void test_abi_title_shows_a_tooltip();
void test_abi_tooltip_dismissal();
void test_abi_paint_cull_keeps_reaching_shadows();
void test_abi_secondary_button_does_not_activate();
void test_abi_context_menu_event();
void test_abi_hover_within_an_ancestor_keeps_its_rules();
void test_abi_hover_reach_bare_pseudo();
void test_abi_hover_reach_by_class();
void test_abi_hover_reach_by_tag();
void test_abi_hover_reach_by_id();
void test_abi_hover_reach_descendant_rule();
void test_abi_hover_reach_negated();
void test_abi_hover_reach_inside_has();
void test_abi_active_reach();
void test_abi_text_decorations_are_drawn();
void test_abi_text_decoration_variants();
void test_abi_text_decoration_styles();
void test_abi_text_decoration_shorthand_paints();
void test_abi_row_identity();
void test_abi_selection_replaces();
void test_abi_selection_is_drawn();
void test_abi_click_places_caret();
void test_abi_drag_selects();
void test_abi_double_click_selects_word();
void test_abi_select_opens_and_chooses();
void test_abi_select_cancels();
void test_abi_select_keys();
void test_abi_select_reflects_choice();
void test_abi_disabled_controls_are_inert();
void test_abi_select_long_list_scrolls();
void test_abi_checkbox_draws_a_tick();
void test_abi_list_box_selects();
void test_abi_list_box_multiple();
void test_abi_ancestor_attribute_reaches_the_cascade();
void test_abi_list_box_scrolls();
void test_abi_form_pseudo_classes();
void test_abi_radio_group();
void test_abi_range_drag();
void test_abi_range_step_and_bounds();
void test_abi_text_field_editing();
void test_abi_set_value_round_trips();
void test_abi_tab_navigation();
void test_abi_embedded_focus_and_text();
void test_abi_keyboard_activation();
void test_abi_ime_composition();
void test_abi_ime_external_mutation();
void test_abi_event_text_payload();
void test_abi_ime_lifecycle();
void test_abi_ime_candidate();
void test_abi_deferred_paint_geometry();
void test_abi_ime_caret_geometry();
void test_abi_implicit_submission();
void test_abi_radio_keyboard_navigation();
void test_abi_range_keyboard();
void test_abi_tabindex_order();
void test_abi_focus_skips_unreachable();
void test_abi_keyboard_events();
void test_abi_text_input();
void test_abi_element_contains();
void test_abi_set_text();
void test_abi_hit_testing();
void test_abi_hit_testing_opt_out();
void test_abi_hit_testing_through_padding();
void test_abi_hover_active_focus();
void test_abi_transition_runs();
void test_abi_transition_costs_nothing_when_idle();
void test_transition_shorthand_lists();
void test_abi_query_and_bounds();
void test_abi_attributes_and_text();
void test_abi_viewport_and_restyle();
void test_abi_content_size();
void test_abi_rounded_rect_primitive();
void test_abi_texture_ids_are_all_published();
void test_abi_host_render_backend();
void test_abi_partial_backend_degrades();
void test_abi_host_font_backend();
void test_abi_registered_font_families();
void test_abi_layout_dump_and_leading();
void test_abi_font_and_renderer_replacement();
void test_abi_positioned_font_shaping();
void test_abi_shape_cache_retains_hot_labels();
void test_abi_shape_cache_bounds_long_labels();
int main() {
    test_arena();
    test_grapheme_conformance();
    test_abi_text_editing_boundaries();
    test_abi_maxlength_insertions();
    test_abi_maxlength_newlines();
    test_abi_maxlength_composition();
    test_abi_input_text_scroll();
    test_abi_text_advances_and_password();
    test_intern();
    test_word_motion_over_ascii();
    test_word_motion_over_punctuation();
    test_word_motion_over_cjk();
    test_word_selection_picks_one_unit();
    test_utf8_walking_never_splits_a_character();
    test_cjk_classification();
    test_accented_latin_is_a_word_character();
    test_geometry();
    test_dom();
    test_validity_selectors_chrome();
    test_range_selectors_chrome();
    test_form_live_defaults();
    test_select_keyboard_ranges();
    test_select_pointer_ranges();
    test_select_display_size();
    test_select_disabled_dropdown();
    test_select_retained_paint();
    test_unicode_typeahead();
    test_select_typeahead_actions();
    test_select_labels();
    test_select_autoscroll();
    test_text_autoscroll();
    test_text_autoscroll_lifecycle();
    test_abi_incremental_text_autoscroll();
    test_abi_incremental_direct_text();
    test_abi_incremental_bindings();
    test_abi_incremental_caret_reuse();
    test_abi_incremental_keyed_reorder();
    test_abi_incremental_container_queries();
    test_abi_incremental_modal_layout();
    test_abi_inline_fragment_bounds();
    test_select_autoscroll_lifecycle();
    test_abi_incremental_select_autoscroll();
    test_abi_incremental_block_margins();
    test_abi_incremental_multicol_sizing();
    test_abi_incremental_collapsed_table_borders();
    test_abi_incremental_has_range_scopes();
    test_abi_incremental_select_color_scopes();
    test_abi_form_reset();
    test_abi_incremental_form_state();
    test_abi_incremental_backdrop_lifecycle();
    test_abi_reset_edit_session();
    test_html();
    test_html_parser();
    test_css_tokenizer();
    test_css_parser();
    test_css_value();
    test_css_color();
    test_css_calc();
    test_selector();
    test_selector_has();
    test_selector_match();
    test_property_registry();
    test_computed_style();
    test_lazy_inheritance();
    test_cascade_order();
    test_cascade_compute();
    test_cascade_layers();
    test_component_expansion();
    test_block_in_inline_empty_fragments();
    test_letter_spacing_restarts_at_a_line_break();
    test_variables();
    test_variables_in_cascade();
    test_media_queries();
    test_container_size_queries();
    test_container_conditional_cascade();
    test_supports();
    test_conditional_rules_in_cascade();
    test_pseudo_elements();
    test_match_cache();
    test_env();
    test_attr();
    test_env_attr_in_cascade();
    test_logical_axes();
    test_logical_in_cascade();
    test_logical_vs_physical_order();
    test_logical_before_substitution();
    test_css_property_index();
    test_easing_curves();
    test_keyframes_parsing();
    test_keyframe_sampling();
    test_keyframes_run();
    test_time_parsing();
    test_value_interpolation();
    test_at_property_descriptor();
    test_at_property_validate();
    test_at_property_in_cascade();
    test_css_wide_keywords();
    test_revert();
    test_revert_layer_rollback();
    test_custom_property_keywords();
    test_box_tree();
    test_box_tree_removal();
    test_box_tree_replace();
    test_box_tree_move_owns_text();
    test_box_geometry();
    test_box_id_stability();
    test_box_reparenting();
    test_box_subtree_storage_lifetime();
    test_box_builder_display();
    test_box_builder_blockification();
    test_anonymous_block_wrapping();
    test_box_builder_text_and_multicol();
    test_resolve_length();
    test_resolve_border_width();
    test_font_size_resolution();
    test_font_size_inheritance_chain();
    test_line_height_resolution();
    test_line_height_inheritance();
    test_box_sides();
    test_aspect_ratio_and_direction();
    test_box_model_edges();
    test_box_model_width();
    test_box_model_min_max();
    test_box_model_height_and_position();
    test_auto_margin_centering();
    test_shorthand_expansion_gap();
    test_shorthand_tokenizer();
    test_shorthand_edges();
    test_anchor_sides();
    test_anchor_far_edge_properties();
    test_anchor_size();
    test_anchor_naming();
    test_anchor_invalid_falls_back();
    test_anchor_percentage();
    test_anchor_registry();
    test_shorthand_columns();
    test_shorthand_flex_flow();
    test_shorthand_text_decoration();
    test_shorthand_border();
    test_shorthand_radius_and_axes();
    test_substitution_defers_expansion();
    test_block_auto_margins();
    test_margin_collapse_rules();
    test_block_stacking();
    test_sibling_margin_collapse();
    test_mixed_sign_chain();
    test_parent_child_collapse();
    test_self_collapsing_block();
    test_barriers_do_not_collapse();
    test_percent_height_chain();
    test_auto_height_clamps();
    test_float_keywords();
    test_float_context_queries();
    test_float_placement();
    test_float_does_not_advance_flow();
    test_clear();
    test_float_bfc_scoping();
    test_font_metrics();
    test_inline_item_collection();
    test_line_breaking();
    test_whitespace_collapsing();
    test_line_metrics_and_align();
    test_shrink_to_fit();
    test_inline_layout_reuse();
    test_forced_breaks();
    test_form_control_baselines();
    test_break_all();
    test_flex_main_axis();
    test_flex_cross_axis();
    test_flex_direction_and_order();
    test_grid_tracks();
    test_grid_items();
    test_grid_areas();
    test_size_containment();
    test_anonymous_box_inherits_line_height();
    test_multicol();
    test_inline_fragment_edges();
    test_flex_min_height_is_not_a_definite_height();
    test_flex_min_max_carry_the_frame();
    test_flex_auto_margins_on_main_axis();
    test_flex_column_item_height_is_definite_for_its_content();
    test_flex_container_min_height_makes_the_main_size_definite();
    test_grid_named_lines_repeat_and_implicit_tracks();
    test_grid_line_placement();
    test_grid_stretch_respects_bounds_and_margins();
    test_grid_alignment();
    test_grid_auto_track_contributions();
    test_absolute_auto_width_shrinks_to_fit();
    test_absolute_descendant_keeps_its_size_after_the_ancestor();
    test_shorthand_font();
    test_flex_fractional_factors_and_padding();
    test_flex_stretch_is_clamped_by_the_items_min_max();
    test_flex_row_min_height_is_the_line_cross_size();
    test_flex_row_max_content_sums_its_items();
    test_letter_spacing_widens_runs();
    test_inline_fragment_height_and_order();
    test_var_in_shorthand_expands_after_substitution();
    test_font_family_registry();
    test_flex_center_is_unsafe();
    test_flex_aspect_ratio_height_is_definite();
    test_grid_item_relaid_in_a_second_pass_drops_the_imposed_height();
    test_inline_wrapped_fragments_keep_element_identity();
    test_letter_spacing_counts_graphemes();
    test_inline_box_opening_at_line_end_has_no_fragment_there();
    test_flex_percent_height_against_an_auto_parent_is_indefinite();
    test_grid_aspect_ratio_border_feedback_preserves_auto_height();
    test_grid_aspect_ratio_item_stretches_one_axis();
    test_flex_wrap();
    test_flex_column_items_do_not_shrink_below_their_content();
    test_flex_row_items_do_not_shrink_below_their_min_content();
    test_var_shorthand_expands_at_its_cascade_position();
    test_inline_em_font_size_resolves_against_the_parent();
    test_max_content_joins_wrapped_lines();
    test_parent_intrinsic_measurements();
    test_flex_abspos_child_static_position_follows_alignment();
    test_grid_track_sizing_functions();
    test_inline_box_edges_take_space_on_the_line();
    test_grid_aspect_ratio_item_takes_the_larger_transfer();
    test_grid_subgrid();
    test_grid_inline_atom_percentage_contribution();
    test_grid_auto_flow_column();
    test_grid_auto_flow_dense();
    test_block_in_inline_splitting();
    test_leading_space_after_an_inline_start_is_dropped();
    test_preserved_newlines_force_line_breaks();
    test_pre_wrap_soft_wraps();
    test_button_vertical_centering_is_flow_only();
    test_intrinsic_width_ignores_auto_margins();
    test_grid_intrinsic_width_is_its_tracks();
    test_top_level_comparison_functions();
    test_flex_wrap_reverse_flips_item_alignment();
    test_flex_baseline_items_size_the_line();
    test_flex_grid_item_formatting_context();
    test_border_box_floors_at_its_own_frame();
    test_aspect_ratio_height_respects_box_sizing();
    test_table_fixed_layout_columns();
    test_table_border_conflicts();
    test_table_border_grid();
    test_table_collapsed_border_geometry();
    test_table_collapsed_border_paint();
    test_table_positioned_content_order();
    test_table_nested_stacking_order();
    test_table_opacity_stacking();
    test_positioned_overflow_containing_blocks();
    test_table_translucent_border_intersections();
    test_table_unequal_border_intersections();
    test_table_collapsed_content_box_width();
    test_table_border_spacing_and_auto_layout();
    test_table_colspan_and_rowspan();
    test_table_cells_stretch_and_vertical_align();
    test_table_row_groups_and_captions();
    test_table_visibility_collapse_and_column_hints();
    test_grid_stretched_rows_feed_back_into_columns();
    test_image_decode();
    test_focus_move();
    test_background_image();
    test_replaced_image_cache();
    test_background_size_independence();
    test_blur_flat_matches_full();
    test_blur_matches_scalar();
    test_replaced_img();
    test_border_image();
    test_background_shorthand();
    test_backdrop_filter_colour();
    test_backdrop_filter_extent();
    test_backdrop_filter_blur();
    test_backdrop_filter_reaches_the_backend();
    test_backdrop_filter_is_under_the_background();
    test_border_as_thick_as_its_radius();
    test_gradient_parsing();
    test_gradient_sampling();
    test_gradient_prepared_color_spans();
    test_background_rasterize_layers();
    test_paint_gradient_backgrounds_and_canvas();
    test_text_transform_at_build();
    test_pseudo_element_boxes();
    test_pseudo_counters_and_quotes();
    test_pseudo_content_from_inline_custom_property();
    test_inline_custom_property_feeds_var();
    test_color_mix();
    test_gradient_calc_stop_position();
    test_paint_form_control_marks();
    test_clip_triangles_polygon();
    test_software_interior_clip_is_invisible();
    test_paint_clip_path_and_rounded_overflow();
    test_paint_clip_follows_descendant_transform();
    test_paint_stacking_order();
    test_color_glyphs();
    test_paint_color_filters();
    test_box_shadow_blur_falloff();
    test_blur_and_padded_rasterize();
    test_paint_transform_rotates_geometry();
    test_font_weight_resolution();
    test_anonymous_block_inherits_text_align();
    test_inline_fragments();
    test_inline_atoms();
    test_cjk_lines_break_between_characters();
    test_cjk_kinsoku_prohibitions();
    test_cjk_does_not_break_latin_runs();
    test_text_overflow_ellipsis();
    test_text_overflow_conditions();
    test_list_markers();
    test_list_marker_ordinals();
    test_list_marker_does_not_inherit_the_items_box();
    test_marker_pseudo_styles_the_marker();
    test_flex_flow_reaches_layout();
    test_text_indent();
    test_tabs_are_expanded_not_measured();
    test_tab_size();
    test_break_word_keeps_words_whole_when_they_fit();
    test_overflow_wrap_break_word();
    test_word_spacing_affects_wrapping();
    test_word_spacing();
    test_relative_positioning();
    test_absolute_containing_block();
    test_absolute_placement();
    test_offsets_and_zindex();
    test_out_of_flow_relayout();
    test_tessellate_rect();
    test_tessellate_rounded();
    test_radii_clamping();
    test_tessellate_border();
    test_tessellate_border_uneven_widths();
    test_paint_decorations();
    test_border_side_colors_and_bevels();
    test_srgb_byte_lookup_exact();
    test_paint_color_resolution();
    test_clip_triangles();
    test_paint_tree_calls();
    test_paint_registered_font_families();
    test_software_raster_coverage();
    test_software_fill_rule();
    test_software_gradient();
    test_software_blending_and_scissor();
    test_software_texture_and_robustness();
    test_software_translation_and_output();
    test_end_to_end_render();
    test_stub_font();
    test_stub_shaping();
    test_glyph_atlas();
    test_text_geometry();
    test_text_end_to_end();
    test_blurred_text_shadow_is_one_blurred_run();
    test_abi_version_and_lifecycle();
    test_abi_stylesheet_replacement();
    test_abi_field_selection_memory();
    test_abi_selection_default_lifecycle();
    test_abi_load_and_update();
    test_abi_incremental_matches_fresh();
    test_abi_incremental_subtree_sequences();
    test_abi_incremental_retained_grid_paint();
    test_abi_draw_versions();
    test_abi_incremental_glyph_preparation();
    test_abi_incremental_flex_intrinsics();
    test_abi_incremental_grid_animation();
    test_abi_incremental_corpus();
    test_abi_incremental_textarea_reflow();
    test_abi_incremental_selector_reach();
    test_abi_events();
    test_abi_checkbox();
    test_abi_caret();
    test_abi_binding_text();
    test_abi_binding_attributes();
    test_c_abi_binding_boolean_attributes();
    test_abi_binding_classes();
    test_abi_binding_without_a_source();
    test_abi_binding_long_values();
    test_abi_binding_value_changes_during_read();
    test_abi_binding_repeat();
    test_abi_binding_repeat_keeps_rows();
    test_abi_binding_repeat_scope();
    test_abi_event_handlers();
    test_abi_change_event();
    test_abi_submit_event();
    test_abi_scroll_event();
    test_abi_append_html();
    test_abi_set_html();
    test_abi_remove_element();
    test_abi_remove_clears_state();
    test_abi_query_all();
    test_abi_mutation_keeps_scroll();
    test_abi_scroll_extent();
    test_abi_scroll_wheel();
    test_abi_scroll_moves_content();
    test_abi_scroll_nested();
    test_abi_scroll_set_and_clamp();
    test_abi_scroll_repaints();
    test_abi_scroll_into_view();
    test_abi_scroll_into_view_nested();
    test_abi_scrollbar_appears();
    test_abi_scrollbar_drag();
    test_abi_scrollbar_track_click();
    test_abi_scrollbar_drag_does_not_click();
    test_abi_hidden_is_not_a_scroller();
    test_abi_scroll_keys();
    test_abi_scroll_keys_yield();
    test_abi_caret_is_drawn();
    test_abi_textarea_edits_its_content();
    test_abi_textarea_newlines();
    test_abi_textarea_line_keys();
    test_abi_textarea_caret();
    test_abi_textarea_scrolls_to_caret();
    test_abi_selection_keys();
    test_abi_word_motion_keys();
    test_abi_word_delete_keys();
    test_abi_document_extent_keys();
    test_abi_word_selection_over_cjk();
    test_abi_undo_groups_typing();
    test_abi_undo_breaks_on_other_edits();
    test_abi_undo_restores_cursor_and_forgets_scripted_writes();
    test_abi_undo_is_per_field();
    test_abi_details_toggles();
    test_abi_details_only_its_own_summary();
    test_abi_details_reports_the_toggle();
    test_abi_dialog_backdrop();
    test_abi_dialog_close_notification();
    test_abi_dialog_cancel_request();
    test_abi_dialog_cancel_survives_notifications();
    test_abi_dialog_escape_policy();
    test_abi_dialog_attribute_open_order();
    test_abi_dialog_return_values();
    test_abi_dialog_form_submission();
    test_abi_dialog_form_submission_overrides();
    test_abi_dialog_submission_lifecycle();
    test_form_required_validation();
    test_form_number_validation();
    test_form_email_validation();
    test_abi_email_validation();
    test_form_url_validation();
    test_form_length_validation();
    test_abi_length_validation();
    test_form_length_edit_origin();
    test_form_temporal_values();
    test_form_temporal_constraints();
    test_form_number_edit_buffer();
    test_abi_number_edit_history();
    test_form_number_filter();
    test_abi_temporal_constraints();
    test_abi_url_validation();
    test_form_custom_validity();
    test_abi_custom_validity();
    test_abi_validity_snapshot();
    test_abi_explicit_validity();
    test_abi_interaction_version();
    test_abi_range_directions();
    test_number_keyboard_steps();
    test_abi_invalid_reporting_lifecycle();
    test_abi_number_submission();
    test_abi_required_submission();
    test_abi_dialog_submission_handler_mutations();
    test_abi_bound_dialog_open_order();
    test_abi_label_activates_its_control();
    test_abi_label_forwarding_edge_cases();
    test_abi_popover_backdrop();
    test_abi_popover_trigger();
    test_abi_popover_target_action();
    test_abi_popover_light_dismiss();
    test_abi_popover_light_dismiss_after_trigger();
    test_abi_popover_escape_walks_the_stack();
    test_abi_popover_joins_the_top_layer();
    test_abi_hit_follows_paint_order();
    test_abi_title_shows_a_tooltip();
    test_abi_tooltip_dismissal();
    test_abi_paint_cull_keeps_reaching_shadows();
    test_abi_secondary_button_does_not_activate();
    test_abi_context_menu_event();
    test_abi_hover_within_an_ancestor_keeps_its_rules();
    test_abi_hover_reach_bare_pseudo();
    test_abi_hover_reach_by_class();
    test_abi_hover_reach_by_tag();
    test_abi_hover_reach_by_id();
    test_abi_hover_reach_descendant_rule();
    test_abi_hover_reach_negated();
    test_abi_hover_reach_inside_has();
    test_abi_active_reach();
    test_abi_text_decorations_are_drawn();
    test_abi_text_decoration_variants();
    test_abi_text_decoration_styles();
    test_abi_text_decoration_shorthand_paints();
    test_abi_row_identity();
    test_abi_selection_replaces();
    test_abi_selection_is_drawn();
    test_abi_click_places_caret();
    test_abi_drag_selects();
    test_abi_double_click_selects_word();
    test_abi_select_opens_and_chooses();
    test_abi_select_cancels();
    test_abi_select_keys();
    test_abi_select_reflects_choice();
    test_abi_disabled_controls_are_inert();
    test_abi_select_long_list_scrolls();
    test_abi_checkbox_draws_a_tick();
    test_abi_list_box_selects();
    test_abi_list_box_multiple();
    test_abi_ancestor_attribute_reaches_the_cascade();
    test_abi_list_box_scrolls();
    test_abi_form_pseudo_classes();
    test_abi_radio_group();
    test_abi_range_drag();
    test_abi_range_step_and_bounds();
    test_abi_text_field_editing();
    test_abi_set_value_round_trips();
    test_abi_tab_navigation();
    test_abi_embedded_focus_and_text();
    test_abi_keyboard_activation();
    test_abi_ime_composition();
    test_abi_ime_external_mutation();
    test_abi_event_text_payload();
    test_abi_ime_lifecycle();
    test_abi_ime_candidate();
    test_abi_deferred_paint_geometry();
    test_abi_ime_caret_geometry();
    test_abi_implicit_submission();
    test_abi_radio_keyboard_navigation();
    test_abi_range_keyboard();
    test_abi_tabindex_order();
    test_abi_focus_skips_unreachable();
    test_abi_keyboard_events();
    test_abi_text_input();
    test_abi_element_contains();
    test_abi_set_text();
    test_abi_hit_testing();
    test_abi_hit_testing_opt_out();
    test_abi_hit_testing_through_padding();
    test_abi_hover_active_focus();
    test_abi_transition_runs();
    test_abi_transition_costs_nothing_when_idle();
    test_transition_shorthand_lists();
    test_abi_query_and_bounds();
    test_abi_attributes_and_text();
    test_abi_viewport_and_restyle();
    test_abi_content_size();
    test_abi_rounded_rect_primitive();
    test_abi_texture_ids_are_all_published();
    test_abi_host_render_backend();
    test_abi_partial_backend_degrades();
    test_abi_host_font_backend();
    test_abi_registered_font_families();
    test_abi_layout_dump_and_leading();
    test_abi_font_and_renderer_replacement();
    test_abi_positioned_font_shaping();
    test_abi_shape_cache_retains_hot_labels();
    test_abi_shape_cache_bounds_long_labels();
    std::printf("%d checks, %d failures\n", wevatest::checks, wevatest::failures);
    return wevatest::failures == 0 ? 0 : 1;
}
