# Exercise the shipped executable, including allocation attribution in every
# workload. Comparing counts catches the profiler counting its own storage.
file(MAKE_DIRECTORY "${WORK}")
set(html "${WORK}/sample.html")
set(css "${WORK}/sample.css")
file(WRITE "${html}" "<div id=p><span>aa bbbb</span><span>cc dddd</span></div>")
file(WRITE "${css}" "html,body{margin:0}#p{display:flex;width:200px;gap:8px}span{background:#09f;padding:4px}")

foreach(mode layout full cold)
    set(flags)
    if(mode STREQUAL "full")
        set(flags --full --mutate=layout)
    elseif(mode STREQUAL "cold")
        set(flags --cold)
    endif()
    foreach(profile OFF ON)
        set(profile_flags)
        if(profile)
            set(profile_flags --profile)
        endif()
        execute_process(COMMAND "${BENCH}" "${html}" "${css}" 3 ${flags} ${profile_flags}
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
        if(NOT result STREQUAL "0" OR NOT output MATCHES "allocations ([0-9]+) \\(([0-9]+) bytes\\)")
            message(FATAL_ERROR "${mode} profile=${profile}: ${result}\n${output}\n${error}")
        endif()
        set(count "${CMAKE_MATCH_1}")
        set(bytes "${CMAKE_MATCH_2}")
        if(count LESS 1 OR bytes LESS 1)
            message(FATAL_ERROR "${mode} reports an empty workload: ${output}")
        endif()
        if(profile)
            if(NOT count EQUAL plain_count OR NOT bytes EQUAL plain_bytes)
                message(FATAL_ERROR "${mode}: profiler changed allocation counts (${plain_count}/${plain_bytes} -> ${count}/${bytes})")
            endif()
            if(NOT output MATCHES "allocation sites.*of [1-9][0-9]* sites" OR NOT error MATCHES "timings include stack capture")
                message(FATAL_ERROR "${mode}: missing attribution report or timing qualification\n${output}\n${error}")
            endif()
        else()
            set(plain_count "${count}")
            set(plain_bytes "${bytes}")
        endif()
    endforeach()
endforeach()

execute_process(COMMAND "${BENCH}" "${html}" "" 3 --cold
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
if(NOT result STREQUAL "0" OR NOT output MATCHES "cold allocations [1-9][0-9]*")
    message(FATAL_ERROR "Empty optional stylesheet failed: ${result}\n${output}\n${error}")
endif()

function(reject expected)
    execute_process(COMMAND "${BENCH}" ${ARGN} RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(result STREQUAL "0" OR NOT error MATCHES "${expected}" OR output MATCHES "mean.*ms")
        message(FATAL_ERROR "Invalid invocation produced no clear failure: ${result}\n${output}\n${error}")
    endif()
endfunction()
reject("cannot read" "${WORK}/missing.html")
reject("cannot read" "${html}" "${WORK}/missing.css" 3)
reject("no passes" "${html}" "${css}" 0)
reject("no passes" "${html}" "${css}" -1)
reject("must run separately" "${html}" "${css}" 3 --profile --sample)
reject("between 1 and 6" "${html}" "${css}" 3 --sample-depth=0)
reject("between 1 and 6" "${html}" "${css}" 3 --sample-depth=7)
if(PLATFORM_WINDOWS)
    reject("requires POSIX SIGPROF" "${html}" "${css}" 3 --sample)
endif()
message(STATUS "Benchmark CLI: all workloads, allocation profiles and rejected inputs pass")
